apiVersion: v1
kind: Pod
metadata:
  name: nginx-secrets-mount-item-envvar-w-ssh
spec:
  volumes:
  - name: ssh
    secret:
      secretName: ssh-key-secret
  containers:
  - name: nginx
    image: nginx:1.7.9
    volumeMounts:
    - name: ssh
      readOnly: true
      mountPath: "/root/.ssh/"
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: credenciales-manifest
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: credenciales-manifest
            key: password
