apiVersion: v1
kind: Service
metadata:
  name: servicio-clusterip
spec:
  type: ClusterIP
  selector:
    app: nginx
    environment: testing-clusterip
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
