apiVersion: v1
kind: Service
metadata:
  name: servicio-nodeport
spec:
  type: NodePort
  selector:
    app: nginx
    environment: testing-nodeport
  ports:
    - protocol: TCP
      port: 80
      nodePort: 32000
