apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-f9bb0d33.efs.eu-west-1.amazonaws.com
    path: "/"
